'use strict';
(()=>{const $=id=>document.getElementById(id),stage=$('stage'),paper=$('paper'),root=document.documentElement,reduced=matchMedia('(prefers-reduced-motion: reduce)');let pages=[],current=0,busy=false,paused=reduced.matches,mapZoom=1,zoom=1.5,hintTimer,sceneAnimations=[];
const prepared=new Map();
function crop(el,p,r={x:0,y:0,width:1,height:1}){el.style.overflow='hidden';const img=new Image();img.src=p.sprite;img.alt='';img.draggable=false;Object.assign(img.style,{position:'absolute',maxWidth:'none',left:(-r.x/r.width*100)+'%',top:(-(p.spriteIndex+r.y)/r.height*100)+'%',width:(100/r.width)+'%',height:(100*p.spritePages/r.height)+'%',display:'block'});el.append(img);return img}
function preparePage(n){if(!pages[n])return Promise.resolve();if(!prepared.has(n)){const p=pages[n];const img=new Image();img.src=p.sprite;const work=img.decode().catch(error=>{prepared.delete(n);throw error});prepared.set(n,work)}return prepared.get(n)}
const mobile=()=>innerWidth<=600;const isMap=()=>pages[current]?.kind==='map';
function hint(text){clearTimeout(hintTimer);$('hint').textContent=text;$('hint').classList.remove('gone');hintTimer=setTimeout(()=>$('hint').classList.add('gone'),4500)}
function fit(){if(!pages.length)return;const r=pages[current].ratio;let w,h;if(isMap()){const base=Math.min(stage.clientWidth,stage.clientHeight*r);w=base*mapZoom;h=w/r;paper.style.marginLeft=Math.max(0,(stage.clientWidth-w)/2)+'px';paper.style.marginTop=Math.max(0,(stage.clientHeight-h)/2)+'px';$('map-level').textContent=Math.round(mapZoom*100)+'%';$('map-out').disabled=mapZoom<=1;$('map-in').disabled=mapZoom>=5}else{w=mobile()?stage.clientWidth:Math.min(stage.clientWidth-110,(stage.clientHeight-36)*r);h=w/r;paper.style.marginLeft=mobile()?'0':'auto';paper.style.marginTop='0'}paper.style.width=Math.max(1,w)+'px';paper.style.height=Math.max(1,h)+'px'}
function animate(el,frames,options){if(paused||reduced.matches)return;const a=el.animate(frames,{duration:750,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards',...options});sceneAnimations.push(a)}
function playScene(){if(!pages.length)return;sceneAnimations.forEach(a=>a.cancel());sceneAnimations=[];if(paused||reduced.matches)return;const p=pages[current],panels=[...paper.querySelectorAll('.panel')];if(p.kind==='map'){animate(paper,[{clipPath:'inset(0 45% 0 45%)',filter:'brightness(.88)'},{clipPath:'inset(0 0% 0 0%)',filter:'brightness(1)'}],{duration:900});return}panels.forEach((el,i)=>{let frames,duration=700,delay=i*100;switch(p.kind){case'cover':frames=[{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'}];delay=i*75;break;case'story':frames=i===0?[{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'}]:[{opacity:0,transform:'translateY(14px)'},{opacity:1,transform:'translateY(0)'}];delay=i*160;break;case'area':frames=i===1?[{opacity:.4,transform:'scale(.965)'},{opacity:1,transform:'scale(1)'}]:[{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'}];duration=900;break;case'exhibit':frames=[{opacity:0,transform:`translateX(${i%2?-18:18}px)`},{opacity:1,transform:'translateX(0)'}];delay=i*180;break;case'city':frames=[{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)'}];delay=i*180;duration=850;break;case'events':frames=[{opacity:0,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}];delay=i*110;break;case'closing':frames=i===2?[{opacity:0,transform:'scale(.98)'},{opacity:1,transform:'scale(1)'}]:[{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'}];delay=i*170;break}animate(el,frames,{duration,delay,fill:'backwards'})});paper.querySelectorAll('.photo').forEach((el,i)=>animate(el,[{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)'}],{duration:1000,delay:250+i*180,fill:'backwards'}))}
function update(){const p=pages[current];$('count').textContent=String(current+1).padStart(2,'0')+' / 23';$('prev').disabled=current===0;$('next').disabled=current===pages.length-1;$('map-tools').hidden=!isMap();$('progress').style.width=(current+1)/pages.length*100+'%';$('announce').textContent=`第 ${current+1} 頁，共 23 頁：${p.title}`;history.replaceState(null,'','#page='+(current+1));document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.page)===current)));for(const i of [current-1,current+1])preparePage(i).catch(()=>{})}
async function go(n,turn=true){n=Math.max(0,Math.min(pages.length-1,n));if(!pages.length||busy||(n===current&&paper.children.length))return;busy=true;let sheet;const loadTimer=setTimeout(()=>{$('load').textContent='正在打開摺頁…';$('load').hidden=false},240);try{const p=pages[n];await preparePage(n);if(turn&&!paused&&!reduced.matches&&paper.children.length){const r=paper.getBoundingClientRect();sheet=document.createElement('div');sheet.className='turn-sheet';sheet.setAttribute('aria-hidden','true');Object.assign(sheet.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});crop(sheet,pages[current]);document.body.append(sheet)}sceneAnimations.forEach(a=>a.cancel());current=n;root.classList.toggle('map-mode',isMap());paper.style.visibility='hidden';paper.className='paper';paper.replaceChildren();const base=document.createElement('div');base.className='page-base';base.setAttribute('role','img');base.setAttribute('aria-label',`第${n+1}頁：${p.title}`);crop(base,p);paper.append(base);for(const part of p.panels){const el=document.createElement('div');el.className='panel'+(part.art?' motion-art':'');el.setAttribute('aria-hidden','true');el.style.top=(part.y*100)+'%';el.style.height=(part.height*100)+'%';crop(el,p,{x:0,y:part.y,width:1,height:part.height});paper.append(el)}for(const part of p.photos){const el=document.createElement('div');el.className='photo';el.setAttribute('aria-hidden','true');Object.assign(el.style,{left:part.x*100+'%',top:part.y*100+'%',width:part.width*100+'%',height:part.height*100+'%'});crop(el,p,{x:part.x,y:part.y,width:part.width,height:part.height});paper.append(el)}const spine=document.createElement('div');spine.className='book-spine';paper.append(spine);if(!isMap())paper.classList.add('scene-ready');mapZoom=isMap()?(mobile()?Math.max(1,innerHeight*.78*p.ratio/stage.clientWidth):1.35):1;fit();stage.scrollTo(0,0);update();clearTimeout(loadTimer);$('load').hidden=true;playScene();paper.style.visibility='';if(sheet){const direction=n>lastPage?-1:1;await sheet.animate([{transform:'perspective(1800px) rotateY(0deg)',opacity:1},{transform:`perspective(1800px) rotateY(${direction*82}deg)`,opacity:.85,offset:.72},{transform:`perspective(1800px) rotateY(${direction*105}deg)`,opacity:0}],{duration:680,easing:'cubic-bezier(.32,.05,.2,1)',fill:'forwards'}).finished;sheet.remove()}lastPage=n;if(isMap())hint(mobile()?'拖動看地圖 · 輕點左右兩側翻頁':'按住拖動地圖 · 輕點左右兩側翻頁');else if(n===0)hint('輕點左右兩側，或左右滑動翻頁')}catch(e){$('load').textContent='頁面載入失敗，點此重試';$('load').hidden=false;$('load').onclick=()=>{paper.replaceChildren();go(n,false)}}finally{clearTimeout(loadTimer);paper.style.visibility='';sheet?.remove();busy=false}}
let lastPage=0;$('prev').onclick=()=>go(current-1);$('next').onclick=()=>go(current+1);document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='ArrowRight'){e.preventDefault();go(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1)}});
let swipe;
stage.addEventListener('pointerdown',e=>{if(!e.isPrimary){swipe=null;return}if(busy||(e.pointerType==='mouse'&&e.button!==0))return;swipe={id:e.pointerId,x:e.clientX,y:e.clientY,left:stage.scrollLeft,top:stage.scrollTop,time:performance.now(),distance:0,map:isMap()};if(e.pointerType==='mouse')stage.setPointerCapture(e.pointerId)});
stage.addEventListener('pointermove',e=>{if(swipe&&swipe.id===e.pointerId)swipe.distance=Math.max(swipe.distance,Math.hypot(e.clientX-swipe.x,e.clientY-swipe.y))});
stage.addEventListener('pointerup',e=>{if(!swipe||swipe.id!==e.pointerId)return;const gesture=swipe;swipe=null;if(busy)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(!gesture.map&&Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){go(current+(dx<0?1:-1));return}const didScroll=Math.abs(stage.scrollLeft-gesture.left)+Math.abs(stage.scrollTop-gesture.top)>4;if(Math.max(gesture.distance,Math.hypot(dx,dy))>10||didScroll||performance.now()-gesture.time>550)return;const bounds=paper.getBoundingClientRect(),left=Math.max(0,bounds.left),right=Math.min(stage.clientWidth,bounds.right),fraction=(e.clientX-left)/(right-left);if(e.clientY<Math.max(0,bounds.top)||e.clientY>Math.min(stage.clientHeight,bounds.bottom))return;if(fraction>=0&&fraction<=.28)go(current-1);else if(fraction>=.72&&fraction<=1)go(current+1)});
stage.addEventListener('pointercancel',()=>swipe=null);

function dragPan(el,enabled){let drag;el.addEventListener('pointerdown',e=>{if(!enabled()||e.pointerType==='touch'||e.button!==0)return;e.preventDefault();drag={x:e.clientX,y:e.clientY,left:el.scrollLeft,top:el.scrollTop};el.setPointerCapture(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();el.scrollLeft=drag.left-(e.clientX-drag.x);el.scrollTop=drag.top-(e.clientY-drag.y)});const stop=()=>{drag=null;el.classList.remove('dragging')};el.addEventListener('pointerup',stop);el.addEventListener('pointercancel',stop);el.addEventListener('lostpointercapture',stop);el.addEventListener('dragstart',e=>e.preventDefault())}dragPan(stage,()=>isMap()&&!busy);dragPan($('zoom-scroll'),()=>true);
function scaleMap(next){const old=mapZoom,x=(stage.scrollLeft+stage.clientWidth/2)/old,y=(stage.scrollTop+stage.clientHeight/2)/old;mapZoom=Math.max(1,Math.min(5,next));fit();stage.scrollTo(Math.max(0,x*mapZoom-stage.clientWidth/2),Math.max(0,y*mapZoom-stage.clientHeight/2))}$('map-in').onclick=()=>scaleMap(mapZoom+.35);$('map-out').onclick=()=>scaleMap(mapZoom-.35);$('map-fit').onclick=()=>{mapZoom=1;fit();stage.scrollTo(0,0)};
function pause(){root.classList.toggle('paused',paused);$('motion').textContent=paused?'播放動畫':'暫停動畫';$('motion').setAttribute('aria-pressed',String(paused));sceneAnimations.forEach(a=>{if(paused)a.finish()});}pause();$('motion').onclick=()=>{paused=!paused;pause();if(!paused)playScene()};reduced.addEventListener('change',e=>{paused=e.matches;pause()});$('replay').onclick=()=>{$('contents').close();playScene()};$('menu').onclick=()=>{$('contents').showModal()};$('close').onclick=()=>$('contents').close();if(!document.fullscreenEnabled)$('full').hidden=true;else $('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();$('contents').close()}catch{$('full').textContent='暫時無法開啟'}};
function sizeZoom(){const p=pages[current],view=$('zoom-scroll');const zw=Math.min(view.clientWidth,view.clientHeight*p.ratio)*zoom;$('zoom-image').style.width=zw+'px';$('zoom-image').style.height=zw/p.ratio+'px';$('scale').textContent=Math.round(zoom*100)+'%';$('less').disabled=zoom<=1;$('more').disabled=zoom>=5}$('zoom').onclick=()=>{if(!pages.length)return;$('zoom-image').replaceChildren();$('zoom-image').setAttribute('aria-label',pages[current].title);crop($('zoom-image'),pages[current]);zoom=1.5;$('contents').close();$('zoom-dialog').showModal();sizeZoom();$('zoom-scroll').scrollTo(0,0)};$('less').onclick=()=>{zoom=Math.max(1,zoom-.5);sizeZoom()};$('more').onclick=()=>{zoom=Math.min(5,zoom+.5);sizeZoom()};$('zoom-close').onclick=()=>$('zoom-dialog').close();document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));addEventListener('resize',()=>{fit();if($('zoom-dialog').open)sizeZoom()});document.addEventListener('visibilitychange',()=>root.classList.toggle('tab-hidden',document.hidden));
fetch('scenes.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{pages=d;pages.forEach((p,i)=>{const b=document.createElement('button');b.dataset.page=i;b.innerHTML=`<span class="thumb" aria-hidden="true"></span><span>`;const thumb=b.querySelector(".thumb");thumb.style.aspectRatio=p.ratio;crop(thumb,p);b.innerHTML+=`${String(i+1).padStart(2,'0')} / ${p.title}</span>`;b.onclick=()=>{$('contents').close();go(i)};$('thumbs').append(b)});const match=location.hash.match(/^#page[=-](\d+)$/);go(match?Number(match[1])-1:0,false)}).catch(()=>{$('load').textContent='無法載入摺頁，請重新整理。'});
})();
